# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1843f7a41b7c249af7d6296bc23ebf28e6588b344041ba37a0d9a3dc1982b46dcebf72c71cd84abefcc0953b22d2d552663d25f431e84035c1c689b67fd01285
test:
  secret_key_base: c904bdf2fa28c39c8a916f3aa03261dd0bec50bc69e140e52a07e36ee6ee6076ea2a809e867bf158790fb575cc3e5909fcaec0c5fcba8a351da9df4b2a3d750e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  GMAIL_USERNAME: 'filmratingapp'
  GMAIL_PASSWORD: 'Jedrek123'
